app = "domantas-next-app"
primary_region = "ams"

[build]
builder = "paketobuildpacks/builder:jammy"

[build.args]
BP_NODE_VERSION = "18.20.4"

[deploy]
release_command = "npx prisma db push"

[http_service]
auto_start_machines = true
auto_stop_machines = true
force_https = true
internal_port = 3_000
min_machines_running = 0
processes = [ "app" ]

[[vm]]
cpu_kind = "shared"
cpus = 1
memory_mb = 256